services:
  postgres:
    image: postgres:16
    container_name: library_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: